### ISSUE TITLE
Tried the Docker sample and skymind/pipelines repo seems to not exist

### ISSUE THREAD

**Issue by jaystary** [SkymindIO/pipelines#1]
Pulling pipeline (skymind/pipelines:1.2.1)...
ERROR: pull access denied for skymind/pipelines, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Did i overlook something

**Comment by ShamsUlAzeem** [comment]
Can you point to the sample that you used? 

I believe we don't have pipelines uploaded in the docker hub repo. Anyway, can you try following the instructions here for building a docker image? https://github.com/SkymindIO/pipelines/blob/master/sample/docker/README.md

Then you'll be able to see the docker image with `docker images`

**Comment by jaystary** [comment]
I did actually ran it from this sample. The issue doesnt show up anymore, so consider it closed, thanks.
